homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

hassio:

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml

default_config:

automation: !include automations.yaml
group: !include ./configs/groups.yaml
script: !include scripts.yaml
sensor: !include ./configs/sensors.yaml
cloud: !include ./configs/cloud.yaml
# panel_iframe: !include ./configs/panel-iframe.yaml
device_tracker: !include ./configs/presence-detection.yaml
tts: !include ./configs/tts.yaml
zha: !include ./configs/zha.yaml
octoprint: !include ./configs/octoprint.yaml
camera: !include ./configs/camera.yaml
# googlehome: !include ./configs/googlehome.yaml
